version: 0.2

phases:
  install:
    commands:      
      - apt-get update -y
      - apt-get install -y python3-pip
      - pip3 install awscli
      - pip3 install aws-sam-cli
  pre_build:
    commands:
      - cp -R ./ERPSalesForceIntegration /codebuild/output
  build:
    commands: 
      - sam build --template ./ERPSalesForceIntegration/template.yaml 
  post_build:
    commands: 
      - echo "Deploying in the post build phase"
      - sam deploy --stack-name transcatPipelineStack --capabilities CAPABILITY_IAM --s3-bucket transcat-pipeline-test-bucket
artifacts:
  files:
    - '**/*'
  name: BuildArtifact
  base-directory: ./ERPSalesForceIntegration
