version: 0.2

phases:
  install: # only for installing packages in the build envirobment
    commands:      
       # Install the AWS CLI version 2
       # - apt-get update && apt-get install -y python3-pip
      - apt-get update -y
      # - yum update -y
      - echo "updated success"
      - apt-get install -y python3-pip
      # - yum install -y python3-pip
      - pip3 install awscli
      - pip3 install aws-sam-cli
  pre_build:
    commands:
      - echo "Copying template.yaml file to expected location"
      # - cp ERPSalesForceIntegration/template.yaml /codebuild/output/src812130917/src/template.yaml
      - ls -R
      - cp -R ./ERPSalesForceIntegration /codebuild/output
      # NOTE: this is wrong as the whole project is already being copied over to the a directory specific to the build /codebuild/output/src430066580/src/ERPSalesForceIntegration...for now just force it through
      # - ls -R /codebuild/output
  build:
    commands: # commands run during the build
      # Build your application using the SAM CLI
      - echo "Building SAM application"
      #- ls -R
      #- ls -R ../../
      - sam build --template ./ERPSalesForceIntegration/template.yaml # NOTE: this is wrong as the whole project
  post_build:
    commands: 
      - echo "Deploying in the post build phase""
      - sam deploy --capabilities CAPABILITY_IAM
artifacts:
  files:
    - '**/*'
  name: BuildArtifact
  base-directory: ./ERPSalesForceIntegration
