version: 0.2

phases:
  install: # only for installing packages in the build envirobment
    commands:      
       # Install the AWS CLI version 2
       # - apt-get update && apt-get install -y python3-pip
      - yum update && yum install -y python3-pip
      - pip3 install awscli
      - pip3 install aws-sam-cli
  build:
    commands: # commands run during the build
      # Build your application using the SAM CLI
      - sam build
