AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Sample Lambda function'

Resources:
  SkeletalLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'ERPSalesForceIntegration::ERPSalesForceIntegration.ExtractTransformLoadErpObjects::SkeletalLambda'
      FunctionName: 'SkeletalLambda'
      Runtime: 'dotnet6'
      CodeUri: '.'
      Description: 'A simple function that takes a string and does a ToUpper'
      MemorySize: 128
      Timeout: 3
  SchedulerFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'SchedulerFunctionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess' 
  SchedulerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'ERPSalesForceIntegration::ERPSalesForceIntegration.ObjectScheduler::SchedulerFunction'
      FunctionName: 'SchedulerFunction'
      Runtime: 'dotnet6'
      CodeUri: '.'
      Description: 'Function determines dependencies of different objects and schedules them accordingly'
      MemorySize: 256
      Timeout: 300 
      Role: !GetAtt SchedulerFunctionRole.Arn  # add a Role property to the function
  ScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule rule to trigger the Lambda function"
      ScheduleExpression: "cron(*/5 * * * ? *)"  # cron expression for triggering the function at 5th minute of every hour
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt SchedulerFunction.Arn
          Id: "TargetFunction"
  ScheduleLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SchedulerFunction
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduleRule.Arn