AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Sample Lambda function'

Resources:
  SkeletalLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'ERPSalesForceIntegration::ERPSalesForceIntegration.ExtractTransformLoadErpObjects::SkeletalLambda'
      FunctionName: 'SkeletalLambda'
      Runtime: 'dotnet6'
      CodeUri: '.'
      Description: 'A simple function that takes a string and does a ToUpper'
      MemorySize: 128
      Timeout: 3
  SkeletalLambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'ERPSalesForceIntegration::ERPSalesForceIntegration.ExtractTransformLoadErpObjects::SkeletalLambda2'
      FunctionName: 'SkeletalLambda2'
      Runtime: 'dotnet6'
      CodeUri: '.'
      Description: 'this is a secondary test function'
      MemorySize: 128
      Timeout: 3
